import Head from 'next/head'
import Image from 'next/image'
import Title from '../componants/Title'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nextbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.ico" />
      </Head>

      <main>
      <Title name='florent' />
      <Title name='Remy' />


      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          {' '} explored by Florent
        </a>
      </footer>
    </div>
  )
}
