import Head from "next/head";
import Image from "next/image";
import Dashboard from "../componants/Dashboard";
import Title from "../componants/Title";
import Footer from "../componants/Footer";
import SliderAudio from "../componants/SliderAudio";

export default function Home() {

	const user = {
		id: 1,
		email: "deflo59@gmail.com",
		name: "Florent",
		isAdmin: true,
	};
  
	return (
		<div>
			<Head>
				<title>Nextbox</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon2.ico" />
			</Head>

			<main>
				<Title name={user.name} />
				{/* {user.isAdmin ? (
					<>
						<p>Bienvenue super admin !</p>
						<Dashboard />
					</>
				) : (
					<p>bienvenue visiteur</p>
				)} */}
			</main>

			<SliderAudio />

			<Footer />
		</div>
	);
}
